// Offline mode: the web app manifest (installable, with its icons) and the service worker the build writes
// to dist/sw.js. The pages, the resume and the solo games keep working without a connection; the online
// modes and the leaderboard come back with it.
import { profile } from "./content.ts";

/** Addresses that are pages, and the cached page each one opens offline (the same HTML the server gives). */
export const OFFLINE_PAGES: Record<string, string> = {
  "/": "/",
  "/en": "/en",
  "/curriculo": "/curriculo",
  "/resume": "/resume",
  "/simples": "/curriculo",
  "/cv": "/curriculo",
  "/simple": "/resume",
  "/snake": "/",
  "/cobrinha": "/",
  "/invaders": "/",
  "/pong": "/",
  "/tetris": "/",
};

export function manifest() {
  return JSON.stringify(
    {
      name: `phas.dev · ${profile.name}`,
      short_name: "phas.dev",
      description: `${profile.name}, ${profile.role.pt}: portfólio em forma de terminal, currículo e jogos.`,
      lang: "pt-BR",
      start_url: "/",
      scope: "/",
      display: "standalone",
      background_color: "#111214",
      theme_color: "#111214",
      icons: [
        { src: "/icon-192.png", sizes: "192x192", type: "image/png" },
        { src: "/icon-512.png", sizes: "512x512", type: "image/png" },
        {
          src: "/icon-maskable-512.png",
          sizes: "512x512",
          type: "image/png",
          purpose: "maskable",
        },
      ],
    },
    null,
    2,
  );
}

/**
 * The service worker. `version` changes with every build that changes a file, so the new worker caches the
 * new files and drops the old cache; `files` are the build's static files to keep (the pages come from
 * OFFLINE_PAGES).
 */
export function serviceWorker(version: string, files: string[]) {
  const pages = [...new Set(Object.values(OFFLINE_PAGES))];
  return `// Generated by the build (src/pwa.ts).
const CACHE = "phas-${version}";
const PAGES = ${JSON.stringify(pages)};
const FILES = ${JSON.stringify(files)};
const OFFLINE_PAGES = ${JSON.stringify(OFFLINE_PAGES)};
// A page that takes longer than this is answered from the cache, and the network copy still refreshes it.
const PAGE_TIMEOUT_MS = 3000;

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches
      .open(CACHE)
      .then((cache) => cache.addAll([...PAGES, ...FILES]))
      .then(() => self.skipWaiting()),
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) =>
        Promise.all(keys.filter((k) => k.startsWith("phas-") && k !== CACHE).map((k) => caches.delete(k))),
      )
      .then(() => self.clients.claim()),
  );
});

self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET") return;
  const url = new URL(request.url);
  // Other sites (analytics), the games' socket and the leaderboard API always go to the network.
  if (url.origin !== location.origin) return;
  if (/^\\/(ws|api|health)(\\/|$)/.test(url.pathname)) return;

  if (request.mode === "navigate") {
    const path = url.pathname.replace(/(.)\\/$/, "$1").toLowerCase();
    const key = OFFLINE_PAGES[path] ?? "/";
    event.respondWith(page(request, key, path in OFFLINE_PAGES));
    return;
  }
  // Hashed files never change: the cache first. Everything else: the cache at once, refreshed behind.
  if (url.pathname.startsWith("/assets/")) {
    event.respondWith(caches.match(request).then((hit) => hit ?? fetchAndKeep(request)));
    return;
  }
  event.respondWith(
    caches.match(request).then((hit) => {
      const fresh = fetchAndKeep(request);
      if (!hit) return fresh;
      event.waitUntil(fresh.catch(() => {}));
      return hit;
    }),
  );
});

/** Pages: the network first (always the latest), the cached copy when offline or too slow. */
function page(request, key, known) {
  const network = fetch(request).then((response) => {
    if (response.ok && known)
      caches.open(CACHE).then((cache) => cache.put(key, response.clone()));
    return response;
  });
  const timeout = new Promise((resolve) => setTimeout(resolve, PAGE_TIMEOUT_MS));
  const cached = () => caches.match(key).then((hit) => hit ?? caches.match("/"));
  return Promise.race([network, timeout.then(cached)])
    .then((response) => response ?? network)
    .catch(() => cached().then((hit) => hit ?? Response.error()));
}

function fetchAndKeep(request) {
  return fetch(request).then((response) => {
    if (response.ok) {
      const copy = response.clone();
      caches.open(CACHE).then((cache) => cache.put(request, copy));
    }
    return response;
  });
}
`;
}
